### ISSUE TITLE
Implement Welcome Screen with Create Account and Login Options

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/verse#3]
**Objective:** Develop a welcome screen that allows users to either create an account or log in.

**Requirements:**
- [x] Design and implement a welcome screen with two main buttons: "Create Account" and "Login".
- [x] Ensure that the welcome screen is visually appealing and user-friendly.
- [x] Integrate navigation logic for each button:
  - "Create Account" button should navigate to the account creation screen.
  - "Login" button should navigate to the login screen.

**Acceptance Criteria:**
- The welcome screen is accessible and displays correctly on various devices.
- Users can see and interact with both "Create Account" and "Login" buttons.
- Clicking on the "Create Account" button navigates the user to the account creation screen.
- Clicking on the "Login" button navigates the user to the login screen.

**Comment by iGEVA** [comment]
#23
