### ISSUE TITLE
Implement Account Creation Screen with Username, Email, and Password Fields

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/verse#4]
**Objective:** Develop a screen that allows users to create a new account.

**Requirements:**
- [ ] Design and implement an account creation screen with fields for name, email, and password.
- [ ] Include a "Create Account" button to submit the registration form.
- [ ] Add validation for input fields to ensure they are correctly filled out and meet requirements (e.g., password strength).
- [ ] Display error messages for any invalid input or if the account already exists.
- [ ] Integrate navigation logic to redirect the user to the main dashboard upon successful account creation.

**Acceptance Criteria:**
- The account creation screen is accessible and displays correctly on various devices.
- Users can enter their name, email, and password.
- Users receive appropriate error messages for invalid input or existing accounts.
- Successful account creation redirects users to the main dashboard.

**Comment by iGEVA** [comment]
#26 
Closed cause incorrect milestone 
Moved to > [Epic 1: User Registration](https://github.com/System-Garcia/verse/milestone/14)
