### ISSUE TITLE
Implement Login Screen with Username/Email and Password Fields

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/verse#5]
**Objective:** Develop a login screen that allows users to log into their accounts.

**Requirements:**
- [x] Design and implement a login screen with fields for username/email and password.
- [x] Include a "Login" button to submit the login form.
- [x] Add validation for input fields to ensure they are correctly filled out.
- [x] Display error messages for incorrect login credentials.
- [x] Integrate navigation logic to redirect the user to the main dashboard upon successful login.

**Acceptance Criteria:**
- The login screen is accessible and displays correctly on various devices.
- Users can enter their username/email and password.
- Users receive appropriate error messages for incorrect credentials or incomplete fields.
- Successful login redirects users to the main dashboard.

**Comment by iGEVA** [comment]
#18
